ci: update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,6 +42,8 @@ jobs:
         run: yarn build
       - name: Setup Pages
         uses: actions/configure-pages@v5
+      - name: Copy CNAME to build directory
+        run: cp CNAME dist/spa/ || echo "CNAME file not found"
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
